# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='text',
        ),
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='ftype',
            field=models.CharField(choices=[('c99', 'c99'), ('yml', 'yml')], max_length=100),
        ),
    ]
