# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171020_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content',
            new_name='text',
        ),
    ]
