# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171020_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
