version: '3'

# Expose ports without publishing them to the host machine - 
# they’ll only be accessible to linked services. Only the 
# internal port can be specified.
# expose:
#   - "80"

services:
  client:
    build: ./client
    restart: on-failure
    ports:
      - "8000:80"

  nginx:
    image: nginx:alpine
    restart: on-failure
    expose:
      - "8000"
    volumes:
      - static:/usr/share/nginx/html/static
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - server

  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=coder_db
      - POSTGRES_DB=coder_db
      - POSTGRES_PASSWORD=coder_db

  server:
    build: ./server
    restart: on-failure
    volumes:
      - ./server:/usr/src/app/
      - static:/usr/src/app/static
    entrypoint: ./entrypoint.sh
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=coder_db
      - DB_USER=coder_db
      - DB_PASSWORD=coder_db
    expose:
      - "8001"
    depends_on:
      - postgres

  pragcc:
    build:
      context: https://github.com/DonAurelio/pragcc.git

  templates:
    build:
      context: https://github.com/DonAurelio/parallel-templates.git


volumes:
  static: