apiVersion: v1
kind: Pod
metadata:
   name: coder-pod

# Pod specifications
# Specification of the desired behavior of the pod
spec:
  containers:
  # - name: client
  #   image: donaurelio/coder_client:1.0
  #   ports:
  #     # Port on which container is listenining 
  #     # internally.
  #     - containerPort: 80

  # - name: nginx
  #   image: nginx:alpine

  - name: server
    image: donaurelio/coder_server:1.0
    ports:
      - containerPort: 80
  
  # - name: pragcc
  #   image: donaurelio/coder_pragcc:1.0
  
  # - name: templates
  #   image: donaurelio/coder_templates:1.0

