apiVersion: v1
kind: ReplicationController
metadata:
  name: coder-server-rc
spec:
  replicas: 2
  # Selects the pod identified with label
  # app: coder-app
  selector:
    app: coder-server-pod
  # Define the set of pods that will be 
  # managed for this replica controller
  template:
    metadata:
      name: coder-server-pod
      labels:
        app: coder-server-pod
    spec:
      volumes:
        - name: static
      containers:
        # Django applications and static files 
        # must be served by nginx
        - name: nginx
          image: donaurelio/coder_nginx:1.0
          volumeMounts:
            - name: static
              mountPath: /usr/share/nginx/html/static
          ports:
            - containerPort: 8000
              # hostPort: 8081
              protocol: TCP

        - name: django
          image: donaurelio/coder_server:1.0
          command: []
          volumeMounts:
            - name: static
              mountPath: /usr/src/app/static
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: DB_HOST
              value: "coder-database-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "coder_db"
            - name: DB_USER
              value: "coder_db"
            - name: DB_PASSWORD
              value: "coder_db"

        - name: pragcc
          image: donaurelio/coder_pragcc:1.0
        
        - name: templates
          image: donaurelio/coder_templates:1.0

