apiVersion: v1
kind: Pod
metadata:
  name: coder-database-pod
  # Labels used to be selected 
  # by other kuberntes's constructs 
  # (Service,Replica Controllers, etc)
  labels: 
    app: coder-database-pod
# Pod specifications
spec:
  volumes:
    - name: static

  containers:
    - name: postgres
      image: postgres
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 5432
      env:
      # Postgres 
      - name: POSTGRES_USER
        value: "coder_db"
      - name: POSTGRES_DB
        value: "coder_db"
      - name: POSTGRES_PASSWORD
        value: "coder_db"
